openapi: 3.0.2
info:
  title: Government Payment Manager Core Connector
  version: '1.0'
  description: >-
    An API to perform a disbursements through mojaloop
  license:
    name: TBD
    url: TBD
servers:
  - url: /
paths:
  /health:
    get:
      operationId: HealthGet
      summary: Health check endpoint
      description: >-
        The HTTP request GET /health is used to return the current status of the
        API.
      tags:
        - health
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'

  /sendmoney:
    post:
      operationId: SendMoney
      description: >-
        This request is used initiate a p2p transfer in mojaloop.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMoneyRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMoneyResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'

components:
  responses:
    '200':
      description: OK
    '400':
      description: Bad Request
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not Found
    '405':
      description: Method Not Allowed
    '406':
      description: Not Acceptable
    '501':
      description: Not Implemented
    '503':
      description: Service Unavailable


  headers:
    Content-Length:
      required: false
      schema:
        type: integer
      description: >-
        The `Content-Length` header field indicates the anticipated size of the
        payload body. Only sent if there is a body.


        **Note:** The API supports a maximum size of 5242880 bytes (5
        Megabytes).
    Content-Type:
      schema:
        type: string
      required: true
      description: >-
        The `Content-Type` header indicates the specific version of the API used
        to send the payload body.
  schemas:
    SendMoneyRequest:
      title: SendMoneyRequest
      type: object
      required:
        - payeeIdType
        - payeeIdValue
        - amount
        - currency
      properties:
        payerIdType: 
          type: string
          example: MSISDN
        payerIdValue: 
          type: string
          example: 1234567890
        payeeIdType: 
          type: string
          example: MSISDN
        payeeIdValue: 
          type: string
          example: 9876543210
        amount: 
          type: string
          example: 100
        currency: 
          type: string
          example: INR
      description: Data model for Disbursement Request
    SendMoneyResponse:
      title: SendMoneyResponse
      type: object
      required:
        - disbursementId
        - payeeList
      properties:
        transferId: 
          type: string
          example: f2957f7a-34c3-11ed-a261-0242ac120002
        currentState: 
          type: string
          example: 'COMPLETED'
        initiatedTimestamp: 
          type: string
          example: 2012-04-23T18:25:43.511Z
        completedTimestamp: 
          type: string
          example: 2012-04-23T18:25:43.511Z
        payeeFspFee: 
          type: string
          example: 3
        payeeFspCommission: 
          type: string
          example: 2
        payeeReceiveAmount: 
          type: string
          example: 100
      description: Data model for SendMoney Response


