apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-dfsp1-pm-core-connector
  labels:
    app.kubernetes.io/name: ml-dfsp1-pm-core-connector
data:
  default.json: |
    {
      "LISTEN_PORT": 3003,
      "HOST": "0.0.0.0",
      "CORS_WHITELIST": ["*"],
      "ALLOW_CREDENTIALS": false,
      "OUTBOUND_ENDPOINT" : "http://ml-simulators-sim-dfsp1-scheme-adapter:4001",
      "BACKEND_ENDPOINT" : "",
      "REQUEST_TIMEOUT" : 2000
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-dfsp1-pm-core-connector
  labels:
    app.kubernetes.io/name: ml-dfsp1-pm-core-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-dfsp1-pm-core-connector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-dfsp1-pm-core-connector
    spec:
      containers:
      - name: core-connector
        image: lalithkota/sp-con-payment-manager-core-connector:develop
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: config-json
          mountPath: /opt/app/dist/config
      volumes:
      - name: config-json
        configMap:
          name: ml-dfsp1-pm-core-connector
---
apiVersion: v1
kind: Service
metadata:
  name: ml-dfsp1-pm-core-connector
  labels:
    app.kubernetes.io/name: ml-dfsp1-pm-core-connector
spec:
  selector:
    app.kubernetes.io/name: ml-dfsp1-pm-core-connector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
