apiVersion: v1
kind: ConfigMap
metadata:
  name: g2p-payment-interoperability-layer
  labels:
    app.kubernetes.io/name: g2p-payment-interoperability-layer
data:
  pil-api-adapter.json: |
    {
      "LISTEN_PORT": 3001,
      "HOST": "0.0.0.0",
      "CORS_WHITELIST": ["*"],
      "ALLOW_CREDENTIALS": false,
      "PAYMENT_EXECUTION_METHOD": "MOJALOOP",
      "PAYER_DFSP_ID": "dfsp1",
      "PAYER_ID_TYPE": "IBAN",
      "PAYER_ID_VALUE": "IC11in02tn040000012345"
    }
  pil-payment-multiplexer.json: |
    {
      "MOJALOOP_CONNECTION_INFO" : [
        {
          "dfspId": "dfsp1",
          "endpoint": "http://ml-dfsp1-pm-core-connector.ml"
        }
      ],
      "REQUEST_TIMEOUT" : 2000
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g2p-payment-interoperability-layer
  labels:
    app.kubernetes.io/name: g2p-payment-interoperability-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: g2p-payment-interoperability-layer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: g2p-payment-interoperability-layer
    spec:
      containers:
      - name: interop-layer
        image: lalithkota/sp-con-payments-interop-layer:develop
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: config-json
          mountPath: /opt/app/dist/config
      volumes:
      - name: config-json
        configMap:
          name: g2p-payment-interoperability-layer
---
apiVersion: v1
kind: Service
metadata:
  name: g2p-payment-interoperability-layer
  labels:
    app.kubernetes.io/name: g2p-payment-interoperability-layer
spec:
  selector:
    app.kubernetes.io/name: g2p-payment-interoperability-layer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
